# src/components/__init__.py
from .general_charts import render_general_charts
from .individual_analysis import render_individual_tab
from .comparison_cities import render_comparison_cities_tab
from .comparison_dates import render_comparison_dates_tab